name: Run linter and Rspecs on main branch
on:
  push:
    branches:
      - main

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install gems
        run: |
          gem install bundler -v 2.2.8
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Rubocop
        run: bundle exec rubocop

  rpsecs:
    name: Rspecs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install gems
        run: |
          gem install bundler -v 2.2.8
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run Rspecs
        run: bundle exec rspec
